### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by psimondk** [archi-contribs/archi-json-plugin#1]
Hi Jean,

What is the status of the plugin?

I saw on the archi discussion list that you were looking into some issues in september? Where they resolved?

**Comment by jbsarrodie** [comment]
Hi,

Issues have been solved in beta 2. I'm now looking into some small enhancements so that's the reason why it's still in beta (but useable).

**Comment by psimondk** [comment]
OK - thanks a lot - then I'll give it a go :)
