### ISSUE TITLE
Import not working on Windows 10 (Archi 3.3.2)

### ISSUE THREAD

**Issue by wouterroos** [archi-contribs/archi-json-plugin#10]
Hi, 

I'm was trying out this plugin (v0.6) but unfortunately I'm not able to import a model (after I've exported it). I tried with both our own model and a 'newly' created one, both without success. After selecting the folder to import from the tool simply doesn't do anything. Is there any way I get some logging as to what went wrong?

Thanks in advance!

**Comment by jbsarrodie** [comment]
Hi,

Could you be more precise on which version of the plugin you use.

This plugin has been adapted for the new version of Archi (4.0) which is still in beta but perfectly usable. If for any reason you want to stick with Archi 3.3.2, then you'll have to use an old version of this plugin (0.2beta).

Regards

**Comment by wouterroos** [comment]
Hi, 

Thank you for the fast response! :) That was the problem, I tried v0.2beta and this seems to work fine. I will discuss with my team if we can upgrade to 4.0 in the future.

**Comment by jbsarrodie** [comment]
Good!

FYI there are several bugs that have been fixed in the latests versions of Grafico (mainly due to conflicts related to views or elements being moved in the model tree hierarchy), so migrated to Archi 4 and Grafico 0.6 is recommended.

**Comment by wouterroos** [comment]
I will take that into account, Thanks!
