### ISSUE TITLE
archi 3.3.2 + grafico 0.6: export yes, import no

### ISSUE THREAD

**Issue by jayveeAtWork** [archi-contribs/archi-json-plugin#11]
In the combination of archi 3.3.2 and grafico 0.6 there is an issue when importing a grafico model: nothing happens. I'm not sure where to get any debugging or failure output from? On the screen, it just remains blank (no model is loaded).

I've tried this with a brand new model just to be sure there's no issue with the model itself, but also there the problem is present.

1. create a new model
2. call it "test"
3. call the default diagram "test" and add an actor called "test" to it
4. export the model via the grafico plugin -> success, I can see the folders and files have been made
5. close the model
6. import the model via the grafico plugin -> nothing happens

**Comment by jbsarrodie** [comment]
Hi,

As described previously, latest version of Grafico are designed to work only with Archi 4. So I'd highly recommend you to upgrade your Archi setup.

Regards
