### ISSUE TITLE
Tried installing on 4.02 and export doesn't appear on pull down

### ISSUE THREAD

**Issue by peterprib** [archi-contribs/archi-json-plugin#13]

**Comment by jbsarrodie** [comment]
Hi,

Could you provide more context (e.g. how did you install it? and what do you mean by "doesn't appear on pull"?) ? I've just tested and everything is fine.

FWIW, you might have a look at the [Collaboration plugin](https://archimatetool.com/plugins) which superseed this plugin.

Regards

**Comment by Phillipus** [comment]
@jbsarrodie I think he means "pull down" menu.

**Comment by Phillipus** [comment]
I tested on Archi 4.1.1. Moved the jar file into the "plugins" folder and restarted Archi:

![image](https://user-images.githubusercontent.com/600504/33599719-e54fa578-d99e-11e7-8433-b235bbabd2c4.png)

**Comment by peterprib** [comment]
My fault accidentally pull source rather than jar.
