### ISSUE TITLE
How to install some plugin in Archi

### ISSUE THREAD

**Issue by sriagustina** [archi-contribs/archi-json-plugin#15]

**Comment by sriagustina** [comment]
I want to install plugin in http://github.com/nik-ponomarev/archimate2alloy but always failde.
any idea how to install that plugin to archi ? thx

**Comment by Phillipus** [comment]
This is the wrong place to ask. Try on the issues page of that plugin 

https://github.com/nik-ponomarev/archimate2alloy/issues

It looks like that is the source code, so you need to build it in Eclipse or ask the author of the plugin to provide a binary and instructions.

**Comment by sriagustina** [comment]
oh, ok sorry.. thank u. I will ask the author directly.
