### ISSUE TITLE
Import does not work with Archi 4 beta

### ISSUE THREAD

**Issue by smileham** [archi-contribs/archi-json-plugin#4]
Hi Guys,

  Looks like the Export is pretty flexible and is coping well with the Archi 4 implementation of the Archimate 3.0 standard.  However, the Import seems to hard code the folders it is looking for when bringing the XML back into Archi (e.g. although it exports a "strategy" folder, I can't see the code to import it).  So I can export the XML structure, but can't seem to Import (and it doesn't give me an error message back either).

Cheers

Steve

**Comment by jbsarrodie** [comment]
Hi,

Yes, the plugin has to be updated a little bit to work with Archi 4. I'm planning to do it this month to have something usable with Archi 4 beta. I'll also add some enhancements and will fix some issues.

Regards,

JB

**Comment by smileham** [comment]
That's great to hear!

Thanks for getting back to me.

Steve

**Comment by jbsarrodie** [comment]
Hi,

A new beta release has been published that is compatible with Archi 4. You can test it ;-)

Regards,

JB

**Comment by smileham** [comment]
That did the trick! One issue though, and it's probably more my Git settings than an issue with the plugin. When I committed to git, it didn't bring the empty /images directory, which caused the import to fail without an error message. I figured it out, but I'm not sure if there is a better way of highlighting the error on import.

**Comment by jbsarrodie** [comment]
This issue with the image folder is known (git never commit empty folders because in fact git commits only files). This will be solved with the upcomming beta, together with a refactoring of the way images are saved and loaded: for the moment I have to save to a temporary .archimate file which impacts the list of recently opened files, this will no more be the case soon.

**Comment by jbsarrodie** [comment]
Fixed in the latest 0.4 version ;-)

**Comment by smileham** [comment]
Just tested on a clean pull directory, works brilliantly!

Cheers

Steve
