### ISSUE TITLE
How to install on Mac

### ISSUE THREAD

**Issue by stefanluyten** [archi-contribs/archi-json-plugin#8]
Hi

I wonder how this plugin can be installed on mac. It's provided as a jar file but Archi assumes this to be a zip (via the import option in the help menu).
Creating a zip that contains this jar file doesn't seem to work 'This is not an Archi plug-in zip file' is what I get), but this was maybe a too obvious approach anyway :-)

How do I install on a mac running Archi 3.3.2?

Thanks !

Stefan

**Comment by Phillipus** [comment]
Hi, you can copy/move the jar file into the Archi.app bundle contents in the "plugins" folder.

**Comment by stefanluyten** [comment]
@Phillipus Phillipus - thanks for your feedback. Can you please help me locating this folder?
Thanks again for your help

Stefan

**Comment by Phillipus** [comment]
Right-click on the Archi app, and select "Show Package Contents" from the menu. In the Finder you will see the "plugins" folder.
